### PR TITLE
Expose via the API the rendering of baked models with transparency.

### PR DESCRIPTION
**Pull request by Phylogeny**
This is the last addition I anticipate wanting for use in Dire's example mod.

### CODE REVIEW

**Comment by AlgorithmX2** [comment]
Honestly not sure if these are really a good addition to the API or not as well, I can see how they are useful, but not in a "C&B Interfacing" sort of way. Those methods are really just generic rendering code.

Let me know what you think about that,

As for the changes themselves.

I think that those would need @SideOnlys? Since those are some client methods and wouldn't work on the server?

I'm inclined to suggest maybe refactoring those so that client methods are in their own class?

Also probably should change the alpha param to accept 0-255 and do the bit shift in the API method before passing it further, I the method in renderHelper is a bit silly in retrospect, probably the result of various refactors and not enough sleep lol.

**Comment by Phylogeny** [comment]
> Honestly not sure if these are really a good addition to the API or not as well, I can see how they are useful, but not in a "C&B Interfacing" sort of way. Those methods are really just generic rendering code.
> 
> Let me know what you think about that,

They are rendering methods that replicate C&B functionality. An important aspect of the API is adding methods that remove the need to reinvent the wheel. Rendering models with transparency is one of those things.

> I think that those would need @SideOnlys? Since those are some client methods and wouldn't work on the server?
> [...]
> Also probably should change the alpha param to accept 0-255 and do the bit shift in the API method before passing it further [...].

I agree. I've just made those changes.

> I'm inclined to suggest maybe refactoring those so that client methods are in their own class?

Well, your `IChiselsAndBitsAddon` implementer gives you an `IChiselAndBitsAPI` instance to use. How would you access these methods if they're not in that interface? After all, `getKeyBinding` is client only and is in `IChiselAndBitsAPI` (with SideOnly client, like you suggest for these).

**Comment by AlgorithmX2** [comment]
> They are rendering methods that replicate C&B functionality. An important aspect of the API is adding methods that remove the need to reinvent the wheel. Rendering models with transparency is one of those things.

Yes, though it seems a bit thin for reasoning to me. But I suppose all the same Its fine.

> Well, your `IChiselsAndBitsAddon` implementer gives you an `IChiselAndBitsAPI` instance to use. How would you access these methods if they're not in that interface? After all, `getKeyBinding` is client only and is in `IChiselAndBitsAPI` (with SideOnly client, like you suggest for these).

I was thinking that maybe there would be a method to call, say getClientAPI() that returned a client API or something. But since getKeybinding is already there, and I'd rather not move it and cause a breaking change for something so trivial as "organization" we can just leave the methods on the main interface.

I might revisit it later during porting, but for now it should be fine.

Anything else you see before I pull it?

**Comment by Phylogeny** [comment]
> Yes, though it seems a bit thin for reasoning to me. But I suppose all the same Its fine.

A mod adds some functionality. You make an addon for that mod and want to replicate that functionality. Then you find that the mod has gone to some length to add that functionality, and that you would have to duplicate alot of code to do so yourself. A primary function of an API is to allow vanilla functionality to performed by addons. The same could be said for many other methods already in the API (like the rotation/mirroring ones I recently added); "Can't you already do that with various other API methods?" Well, yes, but not without needless code duplication. I mean, do you really think it's appropriate for every addon that wants to render C&B's ghost blocks for the sake of fitting in with C&B's style to have to write there own semi-transparent model rendering class? That seems like exactly the kind of thing an API should provide (assuming there's some demand for it).

By all means, let me know if you identify any weakness in that logic.

> I was thinking that maybe there would be a method to call, say getClientAPI() that returned a client API or something. But since getKeybinding is already there, and I'd rather not move it and cause a breaking change for something so trivial as "organization" we can just leave the methods on the main interface.
> 
> I might revisit it later during porting, but for now it should be fine.

Sounds good.

> Anything else you see before I pull it?

No, that's it.

**Comment by AlgorithmX2** [comment]
> A mod adds some functionality. You make an addon for that mod and want to replicate that functionality. Then you find that the mod has gone to some length to add that functionality, and that you would have to duplicate alot of code to do so yourself. A primary function of an API is to allow vanilla functionality to performed by addons. The same could be said for many other methods already in the API (like the ones I just added); "Can't you already do that with various other API methods?" Well, yes, but not without needless code duplication. I mean, do you really think it's appropriate for every addon that wants to render C&B's ghost blocks for the sake of fitting in with C&B's style to have to write there own semi-transparent model rendering class? That seems like exactly the kind of thing an API should provide (assuming there's some demand for it).

Your not wrong, I suppose I was just jaded into thinking that unless the method would be something specific to the inner workings of C&B the API doesn't really need to provide it.

But thinking on it another way, It makes sense to consider C&B as a library for addon's rather then just a standalone mod. Which has its own merits, as it lends to providing a more seamless experience with C&B, and any addons.

**Comment by Phylogeny** [comment]
Ok, I've just pushed the initial commit of Dire's example mod. As soon as you release a new C&B build with the changes made in this PR and the last, I'll be able to release it on CurseForge.

**Comment by AlgorithmX2** [comment]
I've pushed a fresh build out and updated the API version as well.

**Pull request merged**
