### PR TITLE
Fixed ItemStack NPEs by furthering 1.11 port of the API.

### PR DESCRIPTION
**Pull request by Phylogeny**
I'm effectively done porting EBM to 1.11, but need the API ported the rest of the way to release without guaranteed crashes.

### CODE REVIEW

**Comment by AlgorithmX2** [comment]
I think i'll need to do a few other tweaks before I release again. I'll be updating the API Version when I do that.

**Comment by Phylogeny** [comment]
Sounds good. :)

**Comment by AlgorithmX2** [comment]
Alright I think all the API related stuff should be good to go now, I removed the older deprecated methods, and set the default to nonnull let me know if there are any issues with the changes and I'll try and get a new version out today.

**Comment by Phylogeny** [comment]
I haven't encountered any problems after a fair bit of testing, so looks great.

**Pull request merged**
