### PR TITLE
Create ko_kr.json

### PR DESCRIPTION
**Pull request by LunarFactory**

### CODE REVIEW

**Review by marchermans — CHANGES_REQUESTED** [review]
The proposed file is not up to date and is missing a lot of entries.

Please update the file.

**Comment by marchermans** [comment]
Closing this PR since we now use a new system to update translations: <https://crowdin.com/project/chisels-and-bits>

**Comment by SolidBlock-cn** [comment]
I should have seen this. Recommended to make a notice in the readme.md or lang file.

**Comment by SolidBlock-cn** [comment]
> Closing this PR since we now use a new system to update translations: https://crowdin.com/project/chisels-and-bits

Btw why are there so many duplicate strings in the crowdin? Which file should I translate?

**Pull request closed without merging**
